version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    networks:
      eso-dev-network:
        ipv4_address: 10.10.10.2 
    ports:
      - "81:8080"  # Bind port 8080 in container to 80 on host
    volumes:
      - jenkins_home:/var/jenkins_home # Persist Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock # Optional: if you want Jenkins to use Docker on the host

networks:
  eso-dev-network:
    external: true

volumes:
  jenkins_home:

